### PR TITLE
Added function to get all tool ids with corresponding unit tests.

### PR DESCRIPTION
**Pull request by fernandalavalle**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/72)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/mlabns/db/model.py, line 186 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1ot9XcfVhvmQyWmKF:-KE1ot9YAdWvNX3N8td2:-1622604612) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/db/model.py#L186)):*
I feel like the order doesn't actually matter

---

*[server/mlabns/db/model.py, line 193 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1pk4CDxLNLRfhT-Ts:-KE1pk4CDxLNLRfhT-Tt:-1465191373) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/db/model.py#L193)):*
Is this actually enough of a bottleneck that we need to put the data in memcache? It seems like it shouldn't be since it's only called once per status update. Memcache costs us a bit in terms of code/test complexity and it also makes it a little bit more confusing to update mlab-ns with a new tool (we can add it to the datastore, but it'll still be pulling from memcache). Consider dropping the memcache part of this, though the function is still useful because it abstracts the data store from the caller, so in the future we can cache this if we want.

If we need to keep memcache, we should make the memcache key a constant in constants.py

---

*[server/mlabns/db/model.py, line 195 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1oFhZvOPuVZ5cpE4E:-KE1oFhZvOPuVZ5cpE4F:2118693400) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/db/model.py#L195)):*
Do we need to explicitly convert this to a list? Can we specify that this returns "an iterable set of Tool instances"?

---

*[server/mlabns/handlers/update.py, line 335 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1p1TJUxwzSbkMy6dk:-KE1p1TJUxwzSbkMy6dl:1789098622) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/handlers/update.py#L335)):*
Shouldn't this be like:

```
for tool_id in model.get_all_tool_ids():
```

?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-ns/72)*

**Comment by fernandalavalle** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/mlabns/db/model.py, line 193 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1pk4CDxLNLRfhT-Ts:-KE2y5TLIJnS5PgV5qti:-1516733191) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/db/model.py#L193)):*
Ok. Sounds fine, let's table it for now. I haven't looked at performance comparisons, but I agree it seems like it should be fine. 

---

*[server/mlabns/db/model.py, line 195 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1oFhZvOPuVZ5cpE4E:-KE30r2N9iawyEJNCX9p:-1455541071) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/db/model.py#L195)):*
It makes it easier to write tests, and it didn't seem like a big thing to give up. I could buy that not being a good enough reason though.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-ns/72)*

**Comment by mtlynch** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/mlabns/db/model.py, line 195 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE1oFhZvOPuVZ5cpE4E:-KE31t7IjZzZhbOSz1Nr:-1568211079) ([raw file](https://github.com/m-lab/mlab-ns/blob/0e598bb933da68332f22a747ad19d356e97063ef/server/mlabns/db/model.py#L195)):*
I suggest making a wrapper function in the test module and push the list coercion there. We'll want this anyway if we're getting rid of the defined ordering because we'll want a test function that can verify that an unordered iterable set of Tool instances are equal. I think we can do something simple like:

```
assertToolSetsUnorderedEqual(self, set_a, set_b):
  self.assertEqual(len(list(set_a)), len(list(set_b)))
  ids_a = [x.tool_id for x in set_a]
  ids_b = [x.tool_id for x in set_b]
  self.assertListEqual(sorted(ids_a), sorted(ids_b))
```

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-ns/72)*

**Comment by mtlynch** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/tests/test_model.py, line 38 \[r2\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-KE7Bi-C5RhrTiffKDWh:-KE7Bi-DT9poiED74f1s:-1620247568) ([raw file](https://github.com/m-lab/mlab-ns/blob/30d671b43fa04b68db2c79750b28fd86c01cee64/server/mlabns/tests/test_model.py#L38)):*
Should mention in a comment that it assumes equality based on tool ids

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/m-lab/mlab-ns/72#-:-KE7C0jjsRL2n-yzuYa3:1417088721)*

**Pull request merged**
