### PR TITLE
Batch SliverTool status updates. 

### PR DESCRIPTION
**Pull request by fernandalavalle**
This PR primarily replaces individual updates to SliverTools in the datastore to one update per slice.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/82)

### CODE REVIEW

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/mlabns/handlers/update.py, line 380 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-KFjxwzJnx8rJpN-81_Q:-KFjxwzJnx8rJpN-81_R:921827039) ([raw file](https://github.com/m-lab/mlab-ns/blob/9b5bf7f3ce0b67fb182dcab20cd8b177445a7c8c/server/mlabns/handlers/update.py#L380)):*
These changes seem out of scope. What's going on here? Did we accidentally delete the definitions for these constants in a previous PR?

---

*[server/mlabns/handlers/update.py, line 411 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-KFjyRWjWCGT8H1EeoDv:-KFjyRWjWCGT8H1EeoDw:-859223746) ([raw file](https://github.com/m-lab/mlab-ns/blob/9b5bf7f3ce0b67fb182dcab20cd8b177445a7c8c/server/mlabns/handlers/update.py#L411)):*
Can we include the error itself in the error message? It will probably help a lot with debugging.

---

*[server/mlabns/handlers/update.py, line 413 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-KFjyNJG8dPmbGje3PTk:-KFjyNJG8dPmbGje3PTl:-290171243) ([raw file](https://github.com/m-lab/mlab-ns/blob/9b5bf7f3ce0b67fb182dcab20cd8b177445a7c8c/server/mlabns/handlers/update.py#L413)):*
Should be a period instead of comma

---

*[server/mlabns/handlers/update.py, line 414 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-KFjyPmbZWcxnlczqLTl:-KFjyPmbZWcxnlczqLTm:-2136451058) ([raw file](https://github.com/m-lab/mlab-ns/blob/9b5bf7f3ce0b67fb182dcab20cd8b177445a7c8c/server/mlabns/handlers/update.py#L414)):*
by -> be

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/82)*

**Comment by mtlynch** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/82)*

**Comment by fernandalavalle** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/mlabns/handlers/update.py, line 380 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-KFjxwzJnx8rJpN-81_Q:-KFjyi7K9zEqOOJKmL9i:1398830125) ([raw file](https://github.com/m-lab/mlab-ns/blob/9b5bf7f3ce0b67fb182dcab20cd8b177445a7c8c/server/mlabns/handlers/update.py#L380)):*
yeah, I mean we purposefully got rid of them just forgot to update here. Do you want me to make a new PR for this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/82)*

**Comment by mtlynch** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/mlabns/handlers/update.py, line 380 \[r1\]](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-KFjxwzJnx8rJpN-81_Q:-KFk9QBlRhXNlS1rJPTj:-1825915638) ([raw file](https://github.com/m-lab/mlab-ns/blob/9b5bf7f3ce0b67fb182dcab20cd8b177445a7c8c/server/mlabns/handlers/update.py#L380)):*
So normally yeah this should be its own fix, but for the sake of expedience, can you just check this in as is but make sure that when you update the commit description (during squash and merge) to say that it also replaces references to these constants that don't exist anymore?

Also can you file a bug saying we need to replace these magic strings with defined constants? Now there's a subtle interdependency between this line and the following line of nagios_status.py:

```
for address_family in ['', '_ipv6']:
```

Instead, they should be the same defined constant.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/82)*

**Comment by mtlynch** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/82#-:-KFkAT7bCOIszqSNG-_z:1417088721)*

**Pull request merged**
