### PR TITLE
enable testing vs. prod json handling and other bugs

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/127)

### CODE REVIEW

**Comment by nkinkade** [comment]
@yachang: I apologize for the delay in this review. I've added a few small comments, but mostly this is looking good. Thanks!

---

Reviewed 1 of 1 files at r1, 1 of 3 files at r2, 1 of 2 files at r3.
Review status: 3 of 4 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 71 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9kyM5C0Rfj9z7_L1WD:-L9kyM5C0Rfj9z7_L1WE:b8f4sgy) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L71)):*
> ```Python
>         try:
>             project = app_identity.get_application_id()
>             if project is not None and project == 'mlab-nstesting':
> ```

Is `is not None` required here? That is, will the result always be the same, even without it?

---

*[server/mlabns/handlers/update.py, line 80 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9kyqel6lgT9ZfL1eLy:-L9kyqel6lgT9ZfL1eLz:b-tre70p) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L80)):*
> ```Python
> 
>         try:
>             nagios_sites_json = json.loads(urllib2.urlopen(json_file).read())
> ```

NOTE: This may be outside the scope of this PR. Please disregard if you think that it is: You might like to consider changing variable names like this one to remove the `nagios_` (or any references to Nagios, not just that form). The data coming from this URL is not specific to Nagios. The PR that was merged just last week implements fetching status from Prometheus or Nagios, so its good if we can make things that aren't actually related to just Nagios more generic. For example, maybe this could become just `sites_json`? 

---

*[server/mlabns/handlers/update.py, line 83 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l0BLT8OEy3OnmN57I:-L9l0BLT8OEy3OnmN57J:b81u0xq) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L83)):*
> ```Python
>         except urllib2.HTTPError:
>             # TODO(claudiu) Notify(email) when this happens.
>             logging.error('Cannot open %s.', self.SITE_LIST_URL)
> ```

Should the string replacement here be `json_file` instead of `self.SITE_LIST_URL`?

---

*[server/mlabns/handlers/update.py, line 90 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l17oo3v5-BlBRNaKK:-L9l17opBkyBtzJu7B43:bvy7j0m) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L90)):*
> ```Python
>             return util.send_not_found(self)
> 
>         nagios_site_ids = set()
> ```

This may be beyond the scope of your PR, and if so, please ignore this (and the previous mention). This is another example of a reference to Nagios, for something that isn't really related to Nagios.

---

*[server/mlabns/handlers/update.py, line 105 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l3NtW2-AgAIcpM_Qe:-L9l3NtW2-AgAIcpM_Qf:b-iseves) ([raw file](https://github.com/m-lab/mlab-ns/blob/cbda9382936565b1a4b9613cacb21b8b42df54b6/server/mlabns/handlers/update.py#L105)):*
> ```Python
>         for site_id in unchanged_site_ids:
>             logging.info('Site %s unchanged in %s.', site_id,
>                          self.SITE_LIST_URL)
> ```

Thank you for removing this. This was pretty useless logging.

---

*[server/mlabns/handlers/update.py, line 119 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l4-aB5_IO2RcWcgCF:-L9l4-aB5_IO2RcWcgCG:b5knc0t) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L119)):*
> ```Python
>             if (nagios_site[self.SITE_FIELD] in new_site_ids) or (
>                     nagios_site[self.SITE_FIELD] in unchanged_site_ids):
>                 logging.info('Update site %s.', nagios_site[self.SITE_FIELD])
> ```

This is going to cause a good bit of logging, since in general most every site will be unchanged when this runs daily. It's probably not a big issue since it only runs once a day, but it might be nice to only have it log when adding a new site.

---

*[server/mlabns/handlers/update.py, line 129 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l4dhf-gLq1s2j13kY:-L9l4dhf-gLq1s2j13kZ:btupn0m) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L129)):*
> ```Python
> 
>     def update_site(self, nagios_site):
>         """Update a site.
> ```

Since this is both adding and updating sites, could you update  this comment to indicate that it could be either?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-:-L9lDiAP4jYkcN0ApCth:bmlol9r)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 71 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9kyM5C0Rfj9z7_L1WD:-L9pEaWl4BO9vE2_EhTQ:b8z4uwn) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L71)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Is `is not None` required here? That is, will the result always be the same, even without it?
</blockquote></details>

Code modified.

---

*[server/mlabns/handlers/update.py, line 80 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9kyqel6lgT9ZfL1eLy:-L9pEZ9YAnAbaEGIZ0Tl:bouttai) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L80)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

NOTE: This may be outside the scope of this PR. Please disregard if you think that it is: You might like to consider changing variable names like this one to remove the `nagios_` (or any references to Nagios, not just that form). The data coming from this URL is not specific to Nagios. The PR that was merged just last week implements fetching status from Prometheus or Nagios, so its good if we can make things that aren't actually related to just Nagios more generic. For example, maybe this could become just `sites_json`? 
</blockquote></details>

Good call. Thanks!

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 83 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l0BLT8OEy3OnmN57I:-L9pYTrr4CXta7kC_o8h:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L83)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Should the string replacement here be `json_file` instead of `self.SITE_LIST_URL`?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 90 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l17oo3v5-BlBRNaKK:-L9pZgp6Avc5WkjyM-Mv:bs7wumx) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L90)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This may be beyond the scope of your PR, and if so, please ignore this (and the previous mention). This is another example of a reference to Nagios, for something that isn't really related to Nagios.
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 105 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l3NtW2-AgAIcpM_Qe:-L9p_Nzg8Pc9VUdS9ihn:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/cbda9382936565b1a4b9613cacb21b8b42df54b6/server/mlabns/handlers/update.py#L105)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Thank you for removing this. This was pretty useless logging.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 119 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l4-aB5_IO2RcWcgCF:-L9pdG6Q6LGhVn8jWobL:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L119)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

This is going to cause a good bit of logging, since in general most every site will be unchanged when this runs daily. It's probably not a big issue since it only runs once a day, but it might be nice to only have it log when adding a new site.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 129 at r3](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9l4dhf-gLq1s2j13kY:-L9pdxM-2aQebbhpiLYx:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/0ab737c83460622609f506756a16a1d5868227dc/server/mlabns/handlers/update.py#L129)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Since this is both adding and updating sites, could you update  this comment to indicate that it could be either?
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by nkinkade** [comment]
Thanks for these  change @yachang. I have one remaining question. Thanks!

---

Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 185 at r4](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9pi26B02VzP4usSoau:-L9pi26B02VzP4usSoav:begy40e) ([raw file](https://github.com/m-lab/mlab-ns/blob/59586474b6a27f4192e96d415690808b931ee47b/server/mlabns/handlers/update.py#L185)):*
> ```Python
>     """Updates SliverTools' IP addresses."""
> 
>     IP_LIST_URL = 'https://storage.googleapis.com/operator-mlab-oti/metadata/v0/current/mlab-host-ips.txt'
> ```

Maybe add a TODO comment here that there should eventually be a`TESTING_IP_LIST_URL` (like you already do for `TESTING_SITE_LISTURL` above)?? 

---

*[server/mlabns/handlers/update.py, line 313 at r4](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9pkQiu2fUTH-K45uAI:-L9pkQiu2fUTH-K45uAJ:bhywcx3) ([raw file](https://github.com/m-lab/mlab-ns/blob/59586474b6a27f4192e96d415690808b931ee47b/server/mlabns/handlers/update.py#L313)):*
> ```Python
>         # the out-of-date DataStore will be updated next minute by cron job
>         # check_status.
>         if not memcache.set(sliver_tool.tool_id,
> ```

This worries me slightly. If I am correctly understanding how `UpdateStatusHandler` is working it does this:

1. [Reads in current sliver status](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/handlers/update.py#L437) [from memcache](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/db/sliver_tool_fetcher.py#L161) ([falling back on the datastore](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/db/sliver_tool_fetcher.py#L167) if memcache doesn't have the data it wants).
2. [Writes data back to the datastore](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/handlers/update.py#L487).
3. [Updates memcache](https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/handlers/update.py#L493).

If we don't write to the datastore here, and this bit of code happens to trigger after #1 above, but before #3, then would `UpdateStatusHandler` just overwrite what just got written here?

This whole situation is a terrible shortcoming in the code (i.e., not your fault) with multiple processes trying to read and write to both the datastore  and memcache with no coordination.  I'm unsure what the because thing to do here is. Probably we need to address this issue at its root, but maybe not in this PR.

Do you think it might be better to leave the old behavior, since at least it's a somewhat known behavior, rather than introducing this new one?

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-:-L9pn7ET-mifnoRzTUxU:brn3ceo)*

**Comment by yachang** [comment]
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 185 at r4](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9pi26B02VzP4usSoau:-L9pqnPMDd4JYmhtRZEx:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/59586474b6a27f4192e96d415690808b931ee47b/server/mlabns/handlers/update.py#L185)):*
<details><summary><i>Previously, nkinkade wrote…</i></summary><blockquote>

Maybe add a TODO comment here that there should eventually be a`TESTING_IP_LIST_URL` (like you already do for `TESTING_SITE_LISTURL` above)?? 
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127)*

**Comment by yachang** [comment]
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         except db.TransactionFailedError:
>             logging.error('Failed to write IPs of %s (%s, %s) in datastore.',
>                           sliver_tool.fqdn, sliver_tool.sliver_ipv4,
>                           sliver_tool.sliver_ipv6)
> ```
</details>


---

Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[server/mlabns/handlers/update.py, line 313 at r4](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-L9pkQiu2fUTH-K45uAI:-L9q6IUfDfQHxnot_lJ0:bsjlxrs) ([raw file](https://github.com/m-lab/mlab-ns/blob/59586474b6a27f4192e96d415690808b931ee47b/server/mlabns/handlers/update.py#L313)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The old code caused failure when I tried to update the roundrobin information through cron job check_site which runs daily.

The error happened like:

1. The json files contains new roundrobin info.
2. check_site load the new info, and update Data Store ONLY.
3. in next minutes, cron job check_status read the info from memcache and revert the change in Data Store.

The original fix is like:

check_site update Data Store AND memcache w/ all information for all existing site.

But I soon realized, that check_status will update Data Store every minute anyway, so I simplified the code further like what it is like now.

Hopefully this answer your question.
</blockquote></details>

I add back Data Store code anyway, since the result will be the same, and its daily cron job. 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-:-L9q6EimB77r0vfGzerD:b-59bm2f)*

**Comment by nkinkade** [comment]
:lgtm: Thanks, Ya!

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/m-lab/mlab-ns/127#-:-L9qVexg2-aqYqbALbqS:b47ot)*

**Pull request merged**
