### PR TITLE
round robin implementation for mlab-ns

### PR DESCRIPTION
**Pull request by yachang**
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/120)

### CODE REVIEW

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 79 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5oi9Cgbbft6rHlO7D_:-L5oi9Cgbbft6rHlO7Da:bqoiwqw) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L79)):*
> ```Python
>     is 1/n.
>     """
>     RoundRobinSites = ["yyz01", "yyz02", "lba01", "syd02", "syd02", "test01"]
> ```

Hard-coding site configs is not the pattern we want.

Instead, please investigate using datastore as the source of this information. In particular, each datastore site record could contain an additional field indicating whether it should use the "first-online" strategy or "round-robin" strategy.

https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/db/model.py#L57

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 91 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5opvrYiIMZZp1SRnV7:-L5opvrYiIMZZp1SRnV8:bgh3pni) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L91)):*
> ```Python
>                     is_round_robin = True
>                     if random.uniform(0, 1) < 1.0 / float(RRCount[i]):
>                         sites[tool.site_id] = tool
> ```

What if only one machine is online at syd01, and the random number is greater than 1/rrcount?

Would that machine be skipped? Is that what we want?

I expected to see random selection among online machines at each site where RR is enabled.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 91 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5opvrYiIMZZp1SRnV7:-L5oqy6YE3flKcPmLxtb:b-pyrktd) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L91)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

What if only one machine is online at syd01, and the random number is greater than 1/rrcount?

Would that machine be skipped? Is that what we want?

I expected to see random selection among online machines at each site where RR is enabled.
</blockquote></details>

If there is only one server, it will be selected always (line 83, above code)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 91 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5opvrYiIMZZp1SRnV7:-L5osdbB2praYfQ-na4R:b-c88m05) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L91)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

If there is only one server, it will be selected always (line 83, above code)
</blockquote></details>

:+1: - got it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by yachang** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 79 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5oi9Cgbbft6rHlO7D_:-L5t_Rb-JG09KXy0MW_H:bpvrw8z) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L79)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Hard-coding site configs is not the pattern we want.

Instead, please investigate using datastore as the source of this information. In particular, each datastore site record could contain an additional field indicating whether it should use the "first-online" strategy or "round-robin" strategy.

https://github.com/m-lab/mlab-ns/blob/master/server/mlabns/db/model.py#L57
</blockquote></details>

The json files to feed the site datastore was from nagios. Do you know where to modify nagios to add this additional info?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by stephen-soltesz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 79 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5oi9Cgbbft6rHlO7D_:-L5tt3zzx5-EI8vb09Q4:b-3tozie) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L79)):*
<details><summary><i>Previously, yachang wrote…</i></summary><blockquote>

The json files to feed the site datastore was from nagios. Do you know where to modify nagios to add this additional info?
</blockquote></details>

One possibility is to set it directly in datastore. The default value could be false, and manually updated to true on a site-by-site basis. In this case, we would not need to update the sites config from nagios.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 79 at r1](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L5oi9Cgbbft6rHlO7D_:-L6MpeBkV1Nw15_-eAZo:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/e0910dbd16d8f6692aedf0f830fe4b3ac00c3835/server/mlabns/db/sliver_tool_fetcher.py#L79)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

One possibility is to set it directly in datastore. The default value could be false, and manually updated to true on a site-by-site basis. In this case, we would not need to update the sites config from nagios.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by stephen-soltesz** [comment]
This looks much better. Can you show me how you updated the site round robin values?

A few more small improvements, and this should be the last round.

---

Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/bulkloader.yaml, line 134 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N5UzuVhy9Tr1_4Bow:-L6N5UzuVhy9Tr1_4Box:b-dveg7t) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/bulkloader.yaml#L134)):*
> ```YAML
>       import_transform: transform.none_if_empty(int)
>       export_transform: str
>       
> ```

nit: extra whitespace.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 64 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N5ABuRew3Vs-MnCoO:-L6N5ABuRew3Vs-MnCoP:b-50aasu) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L64)):*
> ```Python
>     """
>     sites = {}
>     """ Round Robin Implemetation: For one site, we need to select a 
> ```

Please reserve usage of `"""` for docstrings only. In this case, the `#` comment is preferable.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 78 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N5G4MYDP9gohZ9ADo:-L6N5G4MYDP9gohZ9ADp:bazj5v) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L78)):*
> ```Python
>     When we keep doing this, the probability of each server got selected
>     is 1/n.
>     Currently RoundRobinSites include "yyz01", "yyz02", "lba01", "syd02", "syd02".
> ```

`yyz01` is retired. `syd02` is repeated.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 86 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N4rpnnb9KXFVDA-dr:-L6N4rpoA-HKELdZ7kaK:b-v7ecuh) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L86)):*
> ```Python
>         else:
>             if tool.roundrobin == True:
>                 if tool.site_id not in RoundRobinCounter:
> ```

This condition and the else branch can be combined if RoundRobinCounter is a defaultdict.

`RoundRobinCounter = collections.defaultdict(lambda: 2)`

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 95 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N55_B4BmcuLhNWn5T:-L6N55_B4BmcuLhNWn5U:bu4u0ef) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L95)):*
> ```Python
>                             1) < 1.0 / float(RoundRobinCounter[tool.site_id]):
>                         sites[tool.site_id] = tool
>                     RoundRobinCounter[tool.site_id] = RoundRobinCounter[
> ```

Please use `+= 1`.

---

*[server/mlabns/tests/test_sliver_tool_fetcher.py, line 205 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N6oOQn8JuuGS7XidQ:-L6N6oORgGrNXUVyxy9C:b-ojul3o) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/tests/test_sliver_tool_fetcher.py#L205)):*
> ```Python
>         # Ideally each server should have count around 3333.
>         # The bar of the test was set for 10% variation due to the
>         # random number simulation.
> ```

Are we "simulating" the random numbers? Would it be true to say "The bar of the test was set for 10% to allow for variation caused by randomness of site selection."

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-:-L6N7mTTxCju_DfRts-6:b-ad1rib)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 78 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N5G4MYDP9gohZ9ADo:-L6NBHx48v8n1064gIFC:bgz5ty2) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L78)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

`yyz01` is retired. `syd02` is repeated.
</blockquote></details>

yyz02 retired. should be syd01 and syd02.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 86 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N4rpnnb9KXFVDA-dr:-L6NBG9bJNdheAPQRjTJ:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L86)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

This condition and the else branch can be combined if RoundRobinCounter is a defaultdict.

`RoundRobinCounter = collections.defaultdict(lambda: 2)`
</blockquote></details>

Done.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 95 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N55_B4BmcuLhNWn5T:-L6NBGVs3h1Y2dDD7bJP:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L95)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please use `+= 1`.
</blockquote></details>

Done.

---

*[server/mlabns/tests/test_sliver_tool_fetcher.py, line 205 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N6oOQn8JuuGS7XidQ:-L6N8bGvNn85_9gWvSM5:bsmd4l2) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/tests/test_sliver_tool_fetcher.py#L205)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Are we "simulating" the random numbers? Would it be true to say "The bar of the test was set for 10% to allow for variation caused by randomness of site selection."
</blockquote></details>

Yes. Done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by yachang** [comment]
Review status: 0 of 5 files reviewed at latest revision, 6 unresolved discussions.

---

*[server/bulkloader.yaml, line 134 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N5UzuVhy9Tr1_4Bow:-L6NFE_9r0PzM_uOw-fE:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/bulkloader.yaml#L134)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

nit: extra whitespace.
</blockquote></details>

Done.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 64 at r2](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6N5ABuRew3Vs-MnCoO:-L6ND93C0zu4h3NFXctf:b-896fix) ([raw file](https://github.com/m-lab/mlab-ns/blob/07e93c0b02fb4ef7a7e3c800b424152a7ab125ec/server/mlabns/db/sliver_tool_fetcher.py#L64)):*
<details><summary><i>Previously, stephen-soltesz (Stephen Soltesz) wrote…</i></summary><blockquote>

Please reserve usage of `"""` for docstrings only. In this case, the `#` comment is preferable.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120)*

**Comment by stephen-soltesz** [comment]
:lgtm: - With one last request.

---

Reviewed 1 of 5 files at r2, 1 of 3 files at r3.
Review status: 2 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/mlabns/db/sliver_tool_fetcher.py, line 87 at r3](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-L6NUXKlF0E1k4PsasyC:-L6NUXKmmMASGRc-qBnw:bhqm8dv) ([raw file](https://github.com/m-lab/mlab-ns/blob/ff12f4bbc676d3f590d0abed1801b1e7ace565ae/server/mlabns/db/sliver_tool_fetcher.py#L87)):*
> ```Python
>         else:
>             if tool.roundrobin == True:
>                 if random.uniform(
> ```

Please restructure so the condition can fit on a single line.

For example, making the defaultdict type a float so the cast is unnecessary or calculating an intermediate `threshold` value. The line break on this condition makes it much harder to read.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/m-lab/mlab-ns/120#-:-L6NUryX7NVyFmtO1AfX:bswsv4n)*

**Pull request merged**
