### PR TITLE
Lowers probability of traffic to YVR01 to 0.1 due to discards

### PR DESCRIPTION
**Pull request by nkinkade**
When switch traffic at YVR01 starts to approach 200Mbit/s we start seeing discards at this site. It is a 1g site.

Screenshot from 2020-11-19 11-18-09

This PR lowers the probability of traffic going to YVR01 to try to get the overall traffic and discards at this site down.

---
This change is [Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/248)

### CODE REVIEW

**Review by stephen-soltesz — APPROVED** [review]
I'm worried this will not necessarily help, but I don't know what else to do short of getting additional capacity in the area. :lgtm:

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/248#-:-MMWmRBf6NbTKGiXXPol:b-4rxthz)* status: :shipit: complete! 1 of 1 LGTMs obtained (waiting on @stephen-soltesz)

**Review by nkinkade — COMMENTED** [review]
Yeah. The worry is that these discard events are caused by a smaller number of very fast clients that will still be testing in this location? 

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/248#-:-MMWmm0w52i2fAnfDUE8:b-qjv7v3)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by stephen-soltesz — COMMENTED** [review]
And, it's not clear to me that the longer paths we'll be sending clients along to alternate sites will be preferable from a data quality perspective than some measurements with discards. Could be a good DQ discussion topic.

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/248#-:-MMWppQN259rQEzcjaeE:b-4be2fn)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Review by nkinkade — COMMENTED** [review]
Users in Vancouver would likely be redirected to Seattle, which is pretty close, though in a different country, which could impact the measurement. But like you said, I'm not sure what else to try here other than to reduce the traffic to this site.

> *[Reviewable](https://reviewable.io/reviews/m-lab/mlab-ns/248#-:-MMWvF5y1IwHe0curBWJ:b-vn9lhj)* status: :shipit: complete! 1 of 1 LGTMs obtained

**Pull request merged**
